"""Roadmap data: weeks, books, sources, cross-statute matrix."""

WEEKS = [
    {
        "week": "1–2",
        "title": "Conceptual Base",
        "focus": "Build the mental map. Why companies restructure, and the menu of routes available.",
        "tasks": [
            "Kar & Minakshi — Chapters 1–3: types of restructuring, motivations, M&A theories",
            "Kar & Minakshi — Chapter on India's merger waves",
            "ICSI CS Professional study material — procedural overview chapter",
            "Build a one-page personal taxonomy: merger vs demerger vs slump sale vs buyback vs reduction",
        ],
    },
    {
        "week": "3",
        "title": "Companies Act — Schemes Framework",
        "focus": "Sections 230–232. The procedural backbone of every scheme of arrangement.",
        "tasks": [
            "Ramaiya — Section 230 commentary (compromises and arrangements)",
            "Ramaiya — Section 231 (tribunal powers) and Section 232 (mergers and amalgamations)",
            "Read the CAA Rules, 2016 end-to-end with Rule 6 and Rule 25 specifically marked",
            "Pull and read one sanctioned NCLT merger order; underline the dispositive paragraphs",
        ],
    },
    {
        "week": "4",
        "title": "Companies Act — Special Routes",
        "focus": "Section 233 fast-track, Section 234 cross-border, Section 66 reduction, Section 68 buyback.",
        "tasks": [
            "Section 233 fast-track + Rule 25 — small co. / WOS / holding-subsidiary thresholds",
            "Section 234 + Rule 25A — cross-border mergers and the notified jurisdictions",
            "Section 66 — capital reduction procedure; read alongside NCLT Rules 2016",
            "Section 68–70 — buyback procedure and the Section 67/70 prohibitions",
        ],
    },
    {
        "week": "5",
        "title": "Companies Act — Read Real Schemes",
        "focus": "The fastest way to learn drafting: read what got sanctioned.",
        "tasks": [
            "Read a sanctioned demerger scheme from NCLT portal — note the appointed date logic",
            "Read a sanctioned capital reduction order — note the rationale and minority protection",
            "Read a fast-track merger order — note ROC/RD process flow",
            "Read a cross-border merger order (post-2018) — note the FEMA compliance certificate",
            "Read a rejected scheme — understand what tribunals flag (under-valuation, oppression)",
        ],
    },
    {
        "week": "6",
        "title": "Tax — Amalgamation & Demerger",
        "focus": "The defining tax sections. Most exam-relevant and most client-relevant.",
        "tasks": [
            "Section 2(1B) — definition of amalgamation; three conditions",
            "Section 2(19AA) — definition of demerger; five conditions",
            "Section 47(vi)/(vii) for amalgamation; 47(vib)/(vid) for demerger",
            "Section 49(2)/(2C)/(2D) — cost of acquisition in successor's hands",
            "Section 72A — carry forward of losses on amalgamation (industrial undertaking test)",
            "Section 72A(4) — loss carry forward in demerger; proportionate allocation",
        ],
    },
    {
        "week": "7",
        "title": "Tax — Slump Sale, Buyback, Reduction",
        "focus": "The non-court routes. Often more practical than schemes for mid-sized clients.",
        "tasks": [
            "Section 50B + Section 2(42C) — slump sale mechanics and Rule 11UAE valuation",
            "Section 50CA + Section 56(2)(x) — anti-abuse on unquoted share transfers",
            "Section 115QA buyback tax — track the post-Oct 2024 shift to shareholder taxation",
            "Section 2(22)(d) and capital-reduction taxation; Anarkali Sarabhai principle",
            "Section 47A — the withdrawal of exemption clauses; common audit pitfall",
        ],
    },
    {
        "week": "8",
        "title": "Tax — The IT Act 2025 Mapping",
        "focus": "Build your personal section-mapping sheet. Non-optional now that the 2025 Act is in force.",
        "tasks": [
            "Map Section 2(1B) → corresponding clause in IT Act 2025",
            "Map Section 2(19AA) → corresponding clause in IT Act 2025",
            "Map Section 47 sub-clauses → IT Act 2025 equivalents",
            "Map Section 72A → IT Act 2025 equivalent; note any change in conditions",
            "Map Section 50B and Section 56(2)(x) → IT Act 2025 equivalents",
            "Read at least one Taxmann or Taxsutra digest commentary on the M&A provisions of IT Act 2025",
        ],
    },
    {
        "week": "9",
        "title": "FEMA — Cross-Border Mergers",
        "focus": "The Cross Border Merger Regulations 2018 and the deemed-approval mechanism.",
        "tasks": [
            "Read FEMA (Cross Border Merger) Regulations, 2018 in full",
            "RBI Master Direction on Foreign Investment — the current consolidated text",
            "Nishith Desai paper: Cross-Border Mergers — Regulatory Overview",
            "Map inbound vs outbound merger conditions side-by-side",
            "Understand the 2-year compliance window for non-compliant assets/borrowings",
        ],
    },
    {
        "week": "10",
        "title": "FEMA — Investment Rules & Pricing",
        "focus": "NDI Rules 2019 and ODI Rules 2022 — the foreign exchange overlay on every M&A deal.",
        "tasks": [
            "NDI Rules 2019 — pricing guidelines, entry routes, sectoral caps for non-residents",
            "ODI Rules and Regulations, 2022 — outbound investment for Indian acquirer",
            "Nishith Desai paper: Reverse Flipping — Time to Internalise into India Inc",
            "PN3 implications and 'beneficial owner' tests for neighbouring-country investors",
            "FEMA reporting forms: FC-GPR, FC-TRS, ODI Form, APR — when each triggers",
        ],
    },
    {
        "week": "11",
        "title": "SEBI, Stamp, Competition, GST Overlays",
        "focus": "The four parallel regimes most often missed in tax-only treatment.",
        "tasks": [
            "SAST Regulations 2011 — open offer triggers under Regulation 3 and Regulation 4",
            "LODR Regulation 37 — scheme approval for listed companies; SEBI Master Circular on schemes",
            "Stamp duty: Telangana stamp schedule for schemes of arrangement; compare with Maharashtra",
            "Competition Act — Section 5/6 thresholds; the Deal Value Threshold notification (Sept 2024)",
            "GST: Schedule II, Section 18 ITC transfer on amalgamation, Section 87 transferee liability",
        ],
    },
    {
        "week": "12",
        "title": "IBC as a Restructuring Tool",
        "focus": "Resolution plans and Section 230 schemes during liquidation. The distressed-restructuring path.",
        "tasks": [
            "IBC Sections 30–31 — resolution plan as a corporate restructuring vehicle",
            "Section 230 schemes during liquidation — Regulation 2B of Liquidation Regulations",
            "Tax treatment of write-backs in resolution; Section 79(2)(c) and Section 115BBI",
            "Stamp duty exemption on transfer pursuant to NCLT-approved resolution plan",
            "Final wrap-up: complete the cross-statute matrix on the Matrix tab for your reference",
        ],
    },
]

BOOKS = [
    {
        "title": "Mergers et al — Issues, Implications and Case Law in Corporate Restructuring",
        "author": "S. Ramanujam",
        "publisher": "LexisNexis · 5th Edition · 2025",
        "priority": "Essential — buy first",
        "why": "The desk reference most senior CAs keep. Strongest on case-law analysis and pre/post-scheme secretarial detail. The 5th edition covers reverse-flip strategy, 2025 IBC case law, and recent Bombay/Delhi stamp duty rulings on schemes.",
    },
    {
        "title": "Master Guide to Mergers and Acquisitions in India — Tax & Regulatory",
        "author": "Ernst & Young LLP",
        "publisher": "Taxmann / LexisNexis · check latest edition",
        "priority": "Essential — tax lens",
        "why": "The book for tax structuring. Covers every mode — amalgamation, slump sale, demerger, hive-off, buyback, capital reduction — with flowcharts, tax due diligence, GAAR analysis and cross-border considerations. Verify the latest edition is current with Finance Act 2025.",
    },
    {
        "title": "Mergers, Acquisitions & Corporate Restructuring — Strategies & Practices",
        "author": "Dr. Rabi Narayan Kar & Dr. Minakshi",
        "publisher": "Taxmann · 4th Edition · October 2025",
        "priority": "Strategic foundation",
        "why": "More academic than Ramanujam, but the latest edition is current on the Companies Act, SEBI Takeover Code, Competition Act and IBC. Best for the 'why and when' of choosing a restructuring route.",
    },
    {
        "title": "Corporate Restructuring — Law and Practice",
        "author": "K.R. Sampath",
        "publisher": "Snow White Publications",
        "priority": "Drafting templates",
        "why": "The practitioner's drafting bible. Model schemes of amalgamation, demerger, slump sale agreements, capital reduction petitions, secretarial drafts. Less analytical, very template-driven. Pairs well with Ramanujam.",
    },
    {
        "title": "Guide to the Companies Act",
        "author": "A. Ramaiya",
        "publisher": "LexisNexis · 2-volume set",
        "priority": "Section-by-section reference",
        "why": "Stable, exhaustive commentary on Sections 230–240, 66, 68 and the CAA Rules. You don't read it cover-to-cover — you look up sections. Every CA office should have a copy.",
    },
    {
        "title": "FEMA Manual — with Cross Border Merger Regulations",
        "author": "Taxmann editorial",
        "publisher": "Taxmann · annual edition",
        "priority": "For weeks 9–10",
        "why": "Bare act + RBI Master Directions + Cross Border Merger Regulations 2018 + NDI/ODI rules with commentary. Indispensable for the FEMA piece — no other book consolidates these as cleanly.",
    },
    {
        "title": "The Law and Practice of Income Tax",
        "author": "Kanga, Palkhivala & Vyas",
        "publisher": "LexisNexis",
        "priority": "Underlying tax law",
        "why": "The gold standard for the underlying capital gains, Section 47/49/72A analysis and judicial interpretation. Vinod Singhania's Direct Taxes Law & Practice (Taxmann) is the lighter, more affordable alternative.",
    },
]

SOURCES = [
    {
        "name": "MCA — Acts & Rules e-Book Portal",
        "type": "Primary regulator",
        "url": "https://www.mca.gov.in/content/mca/global/en/acts-rules/ebooks.html",
        "description": "Companies Act 2013, CAA Rules 2016, NCLT Rules 2016 with amendment history. Source of truth for Sections 230–240.",
    },
    {
        "name": "MCA — Notifications & Circulars",
        "type": "Primary regulator",
        "url": "https://www.mca.gov.in/content/mca/global/en/acts-rules/ebooks/notifications.html",
        "description": "Section 233 fast-track extensions and Section 234 notified-jurisdiction updates are published here.",
    },
    {
        "name": "NCLT — Date-wise Orders",
        "type": "Tribunal orders",
        "url": "https://nclt.gov.in/order-judgement-date-wise",
        "description": "Search sanctioned scheme orders date-wise. Read 15–20 to internalise scheme-drafting conventions.",
    },
    {
        "name": "Income-tax Department — Income-tax Act 2025",
        "type": "Primary regulator",
        "url": "https://www.incometaxindia.gov.in/income-tax-act-2025",
        "description": "Official text of the Income-tax Act 2025 (in force from 1 April 2026). The 1961 Act now stands repealed for transactions on or after that date.",
    },
    {
        "name": "RBI — Master Directions",
        "type": "Primary regulator",
        "url": "https://www.rbi.org.in/Scripts/BS_ViewMasDirections.aspx",
        "description": "Master Direction on Foreign Investment in India and the FEMA (Cross Border Merger) Regulations 2018. Current consolidated text.",
    },
    {
        "name": "RBI — FEMA Notifications",
        "type": "Primary regulator",
        "url": "https://www.rbi.org.in/Scripts/BS_FemaNotifications.aspx",
        "description": "NDI Rules 2019 (with all amendments), ODI Rules & Regulations 2022 (Notif. 400). The consolidated PDFs for current pricing and reporting.",
    },
    {
        "name": "SEBI — Regulations Portal",
        "type": "Securities regulator",
        "url": "https://www.sebi.gov.in/sebiweb/home/HomeAction.do?doListing=yes&sid=1&ssid=3&smid=0",
        "description": "SAST 2011 Takeover Code, LODR, ICDR, Buyback Regulations 2018, Delisting Regulations 2021.",
    },
    {
        "name": "SEBI — Master Circular on Scheme of Arrangement",
        "type": "Securities regulator",
        "url": "https://www.sebi.gov.in/legal/master-circulars/jun-2023/master-circular-on-scheme-of-arrangement_72839.html",
        "description": "Consolidated requirements for listed-company schemes (CFD/POD-2/P/CIR/2023/93 + subsequent amendments) — fairness opinion, exchange no-objection, post-listing.",
    },
    {
        "name": "CCI — Combination Regulations",
        "type": "Competition regulator",
        "url": "https://www.cci.gov.in/combination/legal-framwork/regulations",
        "description": "Combinations Regulations 2024, Deal Value Threshold (Sept 2024), and recent approval orders for benchmarking.",
    },
    {
        "name": "IBBI — IBC Resources",
        "type": "Insolvency regulator",
        "url": "https://www.ibbi.gov.in",
        "description": "CIRP Regulations, Liquidation Regulations, resolution plan precedents and the quarterly newsletter. Essential for week 12.",
    },
    {
        "name": "Nishith Desai Associates — Research Papers",
        "type": "Practitioner papers",
        "url": "https://www.nishithdesai.com/Research-Papers.html",
        "description": "M&A Hotline, Tax Issues in M&A Transactions, Cross-Border Mergers Regulatory Overview, Reverse Flipping. The best free practitioner literature in India.",
    },
    {
        "name": "ICAI — Publications",
        "type": "Professional body",
        "url": "https://www.icai.org/post/19464",
        "description": "Technical Guide on Business Combinations, Ind AS 103 Educational Material, M&A background material from the Committee on Corporate Laws.",
    },
    {
        "name": "ICSI — Drafting & Restructuring Guides",
        "type": "Professional body",
        "url": "https://www.icsi.edu/publications/",
        "description": "Drafting of Schemes and the Corporate Restructuring, Insolvency, Liquidation and Winding-Up CS Professional study material.",
    },
    {
        "name": "Taxmann — Research & Daily Digest",
        "type": "Case law tracker",
        "url": "https://www.taxmann.com",
        "description": "Daily digests on Sec 2(1B), 47, 72A, 56(2)(x) and IT Act 2025 jurisprudence. Subscription for full access; headlines are free.",
    },
    {
        "name": "India Code — Statutory Database",
        "type": "Primary law search",
        "url": "https://www.indiacode.nic.in",
        "description": "Government's master statute database. Use to retrieve a specific section's official text quickly, with amendment history.",
    },
]

MATRIX = {
    "columns": [
        "Companies Act 2013",
        "Income-tax (1961 / 2025)",
        "FEMA",
        "SEBI / Stamp",
        "Competition / GST / Other",
    ],
    "rows": [
        [
            "Merger / Amalgamation",
            "Sec 230–232; CAA Rules 2016; appointed date logic",
            "Sec 2(1B); 47(vi)/(vii); 49(2); 72A loss CF; 56(2)(x)",
            "Domestic — N/A unless inbound",
            "LODR Reg. 37 if listed; State stamp on the order",
            "Ind AS 103; Sec 87 GST transferee liability; Sec 18 ITC transfer",
        ],
        [
            "Demerger / Spin-off",
            "Sec 230–232; appointed date + going concern conditions",
            "Sec 2(19AA) five conditions; 47(vib)/(vid); 49(2C)/(2D); 72A(4)",
            "Generally N/A",
            "LODR Reg. 37; SEBI Master Circular on schemes; State stamp",
            "Pro-rata ITC transfer u/s 18 GST; Ind AS 103 acquirer test",
        ],
        [
            "Slump Sale (BTA)",
            "Sec 180(1)(a) member approval if substantial undertaking",
            "Sec 50B + Sec 2(42C); Rule 11UAE FMV; Sec 50CA + 56(2)(x)",
            "NDI Rules if foreign buyer; pricing guidelines",
            "BTA stamp (State-specific); SAST 3/4 if change of control",
            "GST — supply as a going concern is exempt; ITC transfer u/s 18(3)",
        ],
        [
            "Buyback",
            "Sec 68–70; SH-7 / SH-9 filings; Sec 67 prohibition",
            "Sec 115QA — note Oct 2024 shift to shareholder-level taxation",
            "NDI Rules pricing & reporting for non-resident shareholders",
            "SEBI Buyback Regs 2018 if listed; stamp on share certificates",
            "No GST; check FDI sectoral cap before tender route",
        ],
        [
            "Capital Reduction",
            "Sec 66; NCLT approval; creditor protection",
            "Sec 2(22)(d) deemed dividend; capital gains; Anarkali Sarabhai",
            "NDI Rules + pricing if non-resident shareholders involved",
            "LODR if listed; stamp varies by State on NCLT order",
            "Ind AS — equity adjustment; no GST",
        ],
        [
            "Cross-border Merger",
            "Sec 234; Rule 25A; notified jurisdictions only",
            "Sec 47(via)/(vic)/(vicc); Sec 9(1)(i) indirect transfer; GAAR",
            "FEMA (Cross Border Merger) Regs 2018; deemed RBI approval; 2-yr window",
            "NDI pricing on share issue; State stamp; SEBI if listed",
            "PN3 security clearance if neighbouring country; CCI thresholds",
        ],
        [
            "Fast-track Merger (Sec 233)",
            "Sec 233 + Rule 25 — small co. / WOS / holding-sub; RD/ROC route",
            "Same as regular merger — Sec 2(1B) & Sec 47 apply",
            "Now extended to inbound cross-border (MCA notif. Sept 2024)",
            "Stamp same as regular scheme; SEBI N/A if unlisted",
            "Faster — no NCLT; CCI still applies if thresholds met",
        ],
    ],
}
